#!/bin/bash

echo "[***] Build hook running"

docker pull $IMAGE_NAME || true
docker build \
    --cache-from $IMAGE_NAME \
    --compress \
    --build-arg VERSION=$(git describe --tags --always) \
    --build-arg COMMIT=$(git rev-parse HEAD) \
    --build-arg URL=$(git config --get remote.origin.url) \
    --build-arg BRANCH=$(git rev-parse --abbrev-ref HEAD) \
    --build-arg DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
    --pull \
    --tag $IMAGE_NAME .
